[package]
name = "server"
version = "0.1.0"
authors = ["Jason Pang"]
edition = "2018"

[dependencies]
log = "0.4"
fern = { version = "0.5", features = ["colored"] }
chrono = "0.4"
config = { version = "0.9", features = ["hjson"] }
zip = { version = "0.5" }

[profile.release]
opt-level = 3
